//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSolar.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Planetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Planetas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaSolar.Recursos.Planetas", typeof(Planetas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11 años, 315 días y 1,1 horas..
        /// </summary>
        public static string DescripcionJupiter {
            get {
                return ResourceManager.GetString("DescripcionJupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 686,98 días..
        /// </summary>
        public static string DescripcionMarte {
            get {
                return ResourceManager.GetString("DescripcionMarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 88 días..
        /// </summary>
        public static string DescripcionMercurio {
            get {
                return ResourceManager.GetString("DescripcionMercurio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 164 años, 288 días y 13 horas..
        /// </summary>
        public static string DescripcionNeptuno {
            get {
                return ResourceManager.GetString("DescripcionNeptuno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 29 años, 167 días y 6,7 horas..
        /// </summary>
        public static string DescripcionSaturno {
            get {
                return ResourceManager.GetString("DescripcionSaturno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 365 días..
        /// </summary>
        public static string DescripcionTierra {
            get {
                return ResourceManager.GetString("DescripcionTierra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 84 años, 3 días y 15, 66 horas..
        /// </summary>
        public static string DescripcionUrano {
            get {
                return ResourceManager.GetString("DescripcionUrano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 224,701 días..
        /// </summary>
        public static string DescripcionVenus {
            get {
                return ResourceManager.GetString("DescripcionVenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Jupiter {
            get {
                object obj = ResourceManager.GetObject("Jupiter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Marte {
            get {
                object obj = ResourceManager.GetObject("Marte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mercurio {
            get {
                object obj = ResourceManager.GetObject("Mercurio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Neptuno {
            get {
                object obj = ResourceManager.GetObject("Neptuno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Saturno {
            get {
                object obj = ResourceManager.GetObject("Saturno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sol {
            get {
                object obj = ResourceManager.GetObject("Sol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tierra {
            get {
                object obj = ResourceManager.GetObject("Tierra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Urano {
            get {
                object obj = ResourceManager.GetObject("Urano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Venus {
            get {
                object obj = ResourceManager.GetObject("Venus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
